# Site settings
title: My parking
email: myparkingappinfo@gmail.com
description: "Try to look for a parking place? Try myparkingapp"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary:  5BA34D #80B3FF
  secondary: 147C00 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: Startup Team
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/myparkingapp
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: http://github.com/myparkingapp

# Postal address (add as many lines as necessary)
address:
  - line: Kuala Lumpur, Malaysia
  
# Credits content
credits: 'Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
